<?php 
    foreach ($lesThemes as $unTheme){
        if($unTheme->getId()%2){
            print('<div class="main_cards">');
                print('<div class="card_LogoTheme">');
                    print('<img class="logoTheme" src="' . $unTheme->getLogoTheme() . '">');
                print('</div>');
                print('<div class="card_TitleLeft">');
                    print('<h3>'.$unTheme->getName().'</h3>');
                print('</div>');
                print('<div class="cardContent">');
                    print('<p>'.$unTheme->getContenu().'</p>');
                print('</div>');
            print('</div>'); 
        }else{
            print('<div id="main_card" class="main_cards">');
                print('<div class="card_LogoTheme">');
                    print('<img class="logoTheme" src="'.$unTheme->getLogoTheme().'"></img>');
                print('</div>');
                print('<div class="card_TitleRight">');
                    print('<h3>'.$unTheme->getName().'</h3>');
                print('</div>');
                print('<div class="cardContent">');
                    print('<p>'.$unTheme->getContenu().'</p>');
                print('</div>');
            print('</div>');  
        }  
    }
    ?>