<?php

print('<h2 class="ExoTheme">Thème de la viticulture</h2>');
print('<section id="exercicesList">');
foreach ($quizzies as $quiz){
    if($quiz->getIdTheme()== 2){
        print('<div class="card_questionnaire">');
            print('<div class="card_content">');
                print('<div class="card_imgBox">');
                    print('<img class="card_img" src="' . $quiz->getQuizImg() . '">');
                print('</div>');
                print('<div class="card_intitule">');
                    print('<span>'.$quiz->getEntitled().'</span>');
                print('</div>');
                print('<div class="card_buttonBox">');
                    print('<button class="card_button">Commencer -></button>');
                print('</div>');
            print('</div>');    
            print('<table class="consulter_subTheme">');
                print('<thead>');
                    print('<th>Sous-thème</th>');
                    print('<th>Commencer</th>');
                print('</thead>');
                print('<tbody>');
            foreach($quiz->getSubThemes() as $subTheme){
                    print('<tr>');
                        print('<td>'.$subTheme->getName().'</td>');
                        print('<td><a href="index.php?page=question&action=consulter&idsoustheme='.$subTheme->getId().'&idquestionnaire='.$quiz->getId().'">-></a></td>');
                    print('</tr>');
                    }
                print('</tbody>');
            print('</table>');
        print('</div>');
    }
}