<div class="footer">
  <div class="footer_logoContent">
    <div class="footer_logoBox">
      <ul class="footer_listLogo">
        <li class="footer_inlineLogo"><a href="#" target="_blank" title="twitter"><i class="fi fi-brands-twitter"></i></a></li>
        <li class="footer_inlineLogo"><a href="#" target="_blank" title="facebook"><i class="fi fi-brands-facebook"></i></a></li>
        <li class="footer_inlineLogo"><a href="#" target="_blank" title="instagram"><i class="fi fi-brands-instagram"></i></a></li>
        <li class="footer_inlineLogo"><a href="#" target="_blank" title="linkedin"><i class="fi fi-brands-linkedin"></i></a></li>
      </ul>
    </div>
    <div class="footer_linkBox">
      <ul class="footer_listAbout">
        <li class="footer_link"><a href="#" class="footer_textLink">Accueil</a></li>
        <li class="footer_link"><a href="#" class="footer_textLink">A propos</a></li>
        <li class="footer_link"><a href="#" class="footer_textLink">Me contacter</a></li>
        <li class="footer_link"><a href="#" class="footer_textLink">Crédits</a></li>
      </ul>
    </div>
    <div class="footer_newsLetter">
      <h6 class="footer_subtitle">Newsletter</h6>
      <p class="footer_p">Recevez les actualités du site pour en savoir plus sur les nouveautés.</p>
        <div class="footer_input">
          <input type="email" placeholder="Enter your email address" aria-describedby="button-addon1" class="form-control border-0 shadow-0">
          <div class="btn_submitBox">
            <button id="btn_submit" type="submit"><p id="btn_submitText">Envoyer</p></button>
          </div>
        </div>
    </div>
  </div>
</div>
<!-- Copyrights -->
<div class="bg-light py-4">
  <div class="allRights">
    <p class="text-muted mb-0 py-2">© 2023 HowToWine All rights reserved.</p>
  </div>
</div>