<div>
  <div class="footer_logoContent">
    <div class="footer_logoBox"><img src="img/logo.png">
      <ul class="footer_listLogo">
        <li class="footer_inlineLogo"><a href="#" target="_blank" title="twitter"><i class="fa fa-twitter"></i></a></li>
        <li class="footer_inlineLogo"><a href="#" target="_blank" title="facebook"><i class="fa fa-facebook"></i></a></li>
        <li class="footer_inlineLogo"><a href="#" target="_blank" title="instagram"><i class="fa fa-instagram"></i></a></li>
        <li class="footer_inlineLogo"><a href="#" target="_blank" title="pinterest"><i class="fa fa-pinterest"></i></a></li>
        <li class="footer_inlineLogo"><a href="#" target="_blank" title="linkedin"><i class="fa fa-linkedin"></i></a></li>
      </ul>
    </div>
    <div class="footer_linkBox">
      <ul class="footer_listAbout">
        <li class="footer_link"><a href="#" class="footer_textLink">Accueil</a></li>
        <li class="footer_link"><a href="#" class="footer_textLink">A propos</a></li>
        <li class="footer_link"><a href="#" class="footer_textLink">Me contacter</a></li>
        <li class="footer_link"><a href="#" class="footer_textLink">termes</a></li>
      </ul>
    </div>
    <div class="footer_newsLetter">
      <h6 class="footer_subtitle">Newsletter</h6>
      <p class="footer_p">Lorem ipsum dolor sit amet, consectetur adipisicing elit. At itaque temporibus.</p>
        <div class="footer_input">
          <input type="email" placeholder="Enter your email address" aria-describedby="button-addon1" class="form-control border-0 shadow-0">
          <div class="footer_btnBox">
            <button id="footer_submitBtn" type="submit">Envoyer</button>
          </div>
        </div>
    </div>
  </div>
</div>
<!-- Copyrights -->
<div class="bg-light py-4">
  <div class="container text-center">
    <p class="text-muted mb-0 py-2">© 2023 HowToWine All rights reserved.</p>
  </div>
</div>