<?php
$i = 1;
$j = 1;
foreach($questions as $question){
print('<div class="numberQuestion">');
    print('<h3>Question n°'.$i++.'<h3>');
print('</div>');
print('<h4>'.$question->getEntitled().'</h4>');
print('<div id="answerBox">');
    foreach ($question->getAnswers() as $answer){
        print('<div class="reponseBoite"id="reponse'.$answer->getId().'">');
            print('<div id="chooseBox">');
                print('<input type="checkbox" id="checkbox-button-opt-'.$j.'" name="checkbox-option[]" class="hide-checkbox" data-value="'.$answer->getGoodAnwser().'" value="'.$answer->getId().'">');
                print('<label class="checkLabel"for="checkbox-button-opt-'.$j++.'"><div>'.$answer->getContent().'</div>');
            print('</div>');
        print('</div>');
    }
print('</div>');
}
