<div id="demiCercle">
    <div name="btcircle" id="cercle1"><span class="chooseMenu">Niveau amateur</p>
        <div class="rookyContent">
            <div class="cancelBox"><div class="cancel"></div></div>
            <p>Vous êtes novice et souhaitez apprendre les bases de la production de vin cette section est faite pour vous</p>
            <button class="menuBtn">Parcourir...</button>
        </div>
    </div>
    <div name="btcircle" id="cercle2"><span class="chooseMenu">Niveau étudiant</p>
        <div class="mediumContent">
            <div class="cancelBox"><div class="cancel"></div></div>
            <p>Vous êtes novice et souhaitez apprendre les bases de la production de vin cette section est faite pour vous</p>
            <button class="menuBtn">Parcourir...</button>
        </div>
    </div>
    <div name="btcircle" id="cercle3"><span class="chooseMenu">Niveau professionnel</p>
        <div class="confirmContent">
            <div class="cancelBox"><div class="cancel"></div></div>
            <p>Vous êtes novice et souhaitez apprendre les bases de la production de vin cette section est faite pour vous</p>
            <button class="menuBtn">Parcourir...</button>
        </div>
    </div>
</div>