<div id="main_headerTop">

</div>
<div id="main_headerBottom">
    <div id="main_headerLogoBox">
        <a id="homeLink"href="index.php?page=index"><span id="homeText">Accueil</span></a>
        <img id="mainLogo" src="public/img/logo how to wine.png" alt="logo du site">
    </div>
    <nav>
        <ul>
            <li><a href="index.php?page=lecons">Leçons</a></li>
            <li><a href="index.php?page=exercices">Exercices</a></li>
            <li><a href="index.php?page=Photothèque">Photothèque</a></li>
        </ul> 
    </nav>
</div>







