<div id="profilContent">
    <div id="headerProfil">
        <div id="headerLeft">
            <div id="titleBox">
                <?php
                    print('<span id="titleAchievement">'.$informationsProfil->getTitre()->getName().'</span><button class="editButton" id="editTitle">Modifier</button>');    
                ?>
            </div>
            <div id="avatarBox">
                <?php
                    print('<img id="avatar" src="'.$informationsProfil->getPhotoProfil().'" alt="photo de profil">');    
                ?>
            </div>
        </div>
        <div id="headerRight">
        <!-- <span>Compte crée le :</span> -->
        <?php
            print('<span>Pseudo : '.$informationsProfil->getPseudo().'</span><button class="editButton" id="editPseudo">Modifier</button>'); 
            print('<span>Adresse mail : '.$informationsProfil->getEmail().'</span><button class="editButton" id="editMail">Modifier</button>');     
        ?>
        </div>
    </div>
    <div id="bodyProfil">
        <p>Votre progression actuelle :</p>
        <?php
        foreach($answersProfil as $oneAnswer){
                print('<div>'); 
                print('<span>Nom du questionnaire : '.$oneAnswer['NomQuestionnaire'].'<span>'); 
                print('</div>');  
                print('<div>'); 
                print('<span>Sous-thème : '.$oneAnswer['NomSousTheme'].'<span>'); 
                print('</div>'); 
                print('<div>'); 
                print('<span>Nombre de points obtenu : '.$oneAnswer['points'].'<span>'); 
                print('</div>'); 
        }          
        ?>
    </div>
</div>