<div id="profilContent">
    <div id="headerProfil">
        <div id="headerLeft">
            <div id="titleBox">
                <h1 id="titleAchievement"></h1><button id="editTitle">Modifier</button>
            </div>
            <div id="avatarBox"><img src="" alt=""></div>
            <button id="editAvatar">Modifier</button>
        </div>
        <div id="headerRight">
        <span>Compte crée le :</span>
        <span>Pseudo :</span>
        <span>Adresse mail : </span><button id="editMail">Modifier</button>
        </div>
    </div>
    <div id="bodyProfil">
        <p>Vous avez répondu à :</p>
        <p>x questionnaire sur x en Oeonologie</p>
        <p>x questionnaire sur x en Viticulture</p>
        <p>x questionnaire sur x en Dégustation</p>
    </div>
</div>