<?php
	ini_set('display_errors', 'on');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php require "includes/partials/page_head.phtml"; ?>
    <link rel="stylesheet" href="public/styles/reset.css">
    <link rel="stylesheet" href="public/styles/btn_submit.css">
    <link rel="stylesheet" href="public/styles/mainPhoto.css">
    <link rel="stylesheet" href="public/styles/containerText.css">
    <link rel="stylesheet" href="public/styles/nav_element.css">
    <link rel="stylesheet" href="public/styles/footer_element.css">
</head>
<body>
    <header id="main_header">
        <div class="container">
            <?php require "includes/partials/nav_element.phtml"; ?>
        </div>
    </header>
    <main>
        <div id="main_photo"></div>
        <section id="Lecon">
            <div class="container_text">
                <?php
                foreach($lesChapitres as $unChapitre){
                    print($unChapitre->getChapitre());
                    print($unChapitre->getContenu());
                }
                
                ?>
            </div>
        </section>
    </main>
    <footer>
        <div class="container">
            <?php require "includes/partials/footer_element.phtml" ?>
        </div>
    </footer>
</body>
<script type="text/javascript"src="public/scripts/nav_element.js"></script>
<script type="text/javascript"src="public/scripts/btn_submit.js"></script>

</html>