<?php
	ini_set('display_errors', 'on');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php require "includes/partials/page_head.phtml"; ?>
    <link rel="stylesheet" href="public/styles/reset.css">
    <link rel="stylesheet" href="public/styles/mainPhoto.css">
    <link rel="stylesheet" href="public/styles/nav_element.css">
    <link rel="stylesheet" href="public/styles/containerText.css">
    <link rel="stylesheet" href="public/styles/cardExo.css">
    <link rel="stylesheet" href="public/styles/footer_element.css">
</head>
<body>
    <header id="main_header">
        <div class="container">
            <?php require "includes/partials/nav_element.phtml"; ?>
        </div>
    </header>
    <main>
        <div id="<?= setIdByPage($page)?>"></div>
        <div class="container_grid">
            <h1>Sélectionnez un thème sur lequel vous souhaitez vous exercer.</h1>
            <section id="exercicesList">
                <?php require_once "includes/partials/cardExo.phtml" ?>
            </section>
        </div>
    </main>
    <footer>
        <div class="container">
            <?php require "includes/partials/footer_element.phtml" ?>
        </div>
    </footer>
</body>
<script type="text/javascript"src="public/scripts/nav_element.js"></script>
<script type="text/javascript"src="public/scripts/card_questionnaire.js"></script>

</html>