<!DOCTYPE html>
<html lang="en">
<head>
    <?php require "includes/partials/head_element.phtml"; ?>
    <link rel="stylesheet" href="public/styles/homePageRequired.css">
</head>
<body>
    <header id="main_header">
        <div class="container">
            <?php require "includes/partials/nav_element.phtml"; ?>
        </div>
    </header>
    <main>
        <div id="<?= setIdByPage($page)?>"><h1 id="welcome">Bienvenu sur HowToWine</h1></div>
        <section id="main_siteInfo">
            <div class="container">
                <h2>Paufiné vos connaissances sur l'élaboration des vins avec les différents niveaux proposé</h2>

                <?php require "includes/partials/menu_element.phtml"; ?>
                <div class="gridLeftRightLeft">
                    <?php require "includes/partials/cardLeftRightLeft_element.phtml"; ?>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <div class="container">
            <?php require "includes/partials/footer_element.phtml" ?>
        </div>
    </footer>
</body>
<script type="text/javascript"src="public/scripts/menu_burger.js"></script>
<script type="text/javascript"src="public/scripts/nav_element.js"></script>
<script type="text/javascript"src="public/scripts/index_menu.js"></script>
<script type="text/javascript"src="public/scripts/card_element.js"></script>
</html>