<?php
	ini_set('display_errors', 'on');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php require "includes/partials/head_element.phtml"; ?>
    <link rel="stylesheet" href="public/styles/quizPageRequired.css">
   
</head>
<body>
    <header id="main_header">
        <div class="container">
            <?php require "includes/partials/nav_element.phtml"; ?>
        </div>
    </header>
    <main>
        <div id="<?= setIdByPage($page)?>"></div>
        <div class="container_question">
            <form action="index.php?page=question&action=repondre&idsoustheme=<?=$idSubTheme?>&idquestionnaire=<?=$idQuiz?>" method="post">
                <?php require "includes/partials/frm_question.phtml"; ?>
                <div id="submitButton">
                    <?php
                        if (isset($_SESSION['login']) && $_SESSION['login'] != ''){
                            print('<button type="submit">Voir les résultats</button>');
                        }else{
                            print('<button id="getNote" type="button">Voir les résultats</button>');
                        }
                        ?>
                    <button type="reset">Réinitialiser</button>
                </div>
            </form>
        </div>
    </main>
    <footer>
        <div class="container">
            <?php require "includes/partials/footer_element.phtml" ?>
        </div>
    </footer>
</body>
<script type="text/javascript"src="public/scripts/nav_element.js"></script>
<script type="text/javascript"src="public/scripts/frm_question.js"></script>
</html>