<!DOCTYPE html>
<html lang="en">
<head>
    <?php require "includes/partials/head_element.phtml"; ?>
    <link rel="stylesheet" href="public/styles/profilPage.css">
</head>
<body>
    <header id="main_header">
        <div class="container">
            <?php require "includes/partials/nav_element.phtml"; ?>
        </div>
    </header>
    <main>
        <section id="profil">
            <div class="container_text">
                <div id="profilContainer">
                    <?php require "includes/partials/profil_element.phtml"; ?>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <div class="container">
            <?php require "includes/partials/footer_element.phtml" ?>
        </div>
    </footer>
</body>
<script type="text/javascript"src="public/scripts/menu_burger.js"></script>
<script type="text/javascript"src="public/scripts/nav_element.js"></script>
<script type="text/javascript"src="public/scripts/frm_question.js"></script>
</html>