<!DOCTYPE html>
<html lang="en">
<head>
    <?php require "includes/partials/head_element.phtml"; ?>
    <link rel="stylesheet" href="public/styles/quizListRequired.css">
</head>
<body>
    <header id="main_header">
        <div class="container">
            <?php require "includes/partials/nav_element.phtml"; ?>
        </div>
    </header>
    <main>
        <div id="<?= setIdByPage($page)?>"></div>
        <div class="container_grid">
            <h1>Sélectionnez un thème sur lequel vous souhaitez vous exercer.</h1>
            <div>
                <?php require_once "includes/partials/cardExoOeno.phtml" ?>
            </div>
            <div>
                <?php require_once "includes/partials/cardExoViti.phtml" ?>
            </div>
            <div>
                <?php require_once "includes/partials/cardExoSchema.phtml" ?>
            </div>
        </div>
    </main>
    <footer>
        <div class="container">
            <?php require "includes/partials/footer_element.phtml" ?>
        </div>
    </footer>
</body>
<script type="text/javascript"src="public/scripts/menu_burger.js"></script>
<script type="text/javascript"src="public/scripts/nav_element.js"></script>
<script type="text/javascript"src="public/scripts/card_questionnaire.js"></script>

</html>