<?php
	ini_set('display_errors', 'on');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php require "includes/partials/page_head.phtml"; ?>
    <link rel="stylesheet" href="public/styles/reset.css">
    <link rel="stylesheet" href="public/styles/main_header.css">
    <link rel="stylesheet" href="public/styles/mainPhoto.css">
    <link rel="stylesheet" href="public/styles/nav_element.css">
    <link rel="stylesheet" href="public/styles/menu_element.css">
    <link rel="stylesheet" href="public/styles/cardLeftRightLeft_element.css">
    <link rel="stylesheet" href="public/styles/footer_element.css">
</head>
<body>
    <header id="main_header">
        <div class="container">
            <div id="main_headerTop">

            </div>
            <div id="main_headerBottom">
                <div><img id="mainLogo" src="public/img/logo how to wine.png" alt="logo du site"></div>
                <nav>
                    <?php require "includes/partials/nav_element.phtml"; ?> 
                </nav>
            </div>
        </div>
    </header>
    <main>
        <div id="main_photo"></div>
        <section id="main_siteInfo">
            <div class="container">
                <div>
                    <?php require "includes/partials/menu_element.phtml"; ?>
                </div>
                <div class="gridLeftRightLeft">
                    <?php require "includes/partials/cardLeftRightLeft_element.phtml"; ?>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <div class="container">
            <?php require "includes/partials/footer_element.phtml" ?>
        </div>
    </footer>
</body>
<script type="text/javascript"src="public/scripts/script.js"></script>
</html>