<?php
	ini_set('display_errors', 'on');
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <?php require "includes/partials/head_page.phtml"; ?>
    <link rel="stylesheet" href="public/styles/homePageRequired.css">
</head>
<body>
    <header id="main_header">
        <div class="container">
            <?php require "includes/partials/nav_element.phtml"; ?>
        </div>
    </header>
    <main>
        <div id="<?= setIdByPage($page)?>"></div>
        <section id="main_siteInfo">
            <div class="container">
                <div>
                    <?php require "includes/partials/menu_element.phtml"; ?>
                </div>
                <div class="gridLeftRightLeft">
                    <?php require "includes/partials/cardLeftRightLeft_element.phtml"; ?>
                </div>
            </div>
        </section>
    </main>
    <footer>
        <div class="container">
            <?php require "includes/partials/footer_element.phtml" ?>
        </div>
    </footer>
</body>
<script type="text/javascript"src="public/scripts/nav_element.js"></script>
<script type="text/javascript"src="public/scripts/index_menu.js"></script>
<script type="text/javascript"src="public/scripts/card_element.js"></script>
</html>